POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvYi5tb25kYXlAZ21haWwuY29tIiwiaWQiOjEsImlhdCI6MTY3Mzk5NDY1N30.gCRXCTocOn4V74O0PRevz8rcApHnhFv-3pCE_bJcua8

{
  "title": "cooking with cans",
  "author": "rob m",
  "url": "www.amateurhourcooking.com",
  "likes": 0
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvYi5tb25kYXlAZ21haWwuY29tIiwiaWQiOjEsImlhdCI6MTY3Mzk5NDY1N30.gCRXCTocOn4V74O0PRevz8rcApHnhFv-3pCE_bJcua8

{
  "title": "cooking from the finer things club",
  "author": "jennie m",
  "url": "www.procooking.com",
  "likes": 0
}