POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "rob.monday@gmail.com",
  "name": "Rob Monday"
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "jenniem@yahoo.com",
  "name": "Jennie Monday"
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "admin@yahoo.com",
  "name": "administrator user"
}